### ISSUE TITLE
需要的是在xml 里面就完成Divider

### ISSUE THREAD

**Issue by VectorWen** [nekocode/DividerDrawable#2]
一般是在写布局文件就完成了线条的布局，代码里面基本是包括线条的处理了。
在预览的时候也是需要能看到布局。

**Comment by nekocode** [comment]
Android 系统并不允许在 XML 中对 Drawable 进行 Attribute 的配置，所以你没法在 XML 中对 Drawable 进行动态布局。需要在预览的时候看到布局的话还请使用 View 吧。
